apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tb2l4ydzi-python
  janus-idp.io/tekton: tb2l4ydzi-python
  backstage.io/kubernetes-id: tb2l4ydzi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tb2l4ydzi-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
