apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tb2l4ydzi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tb2l4ydzi-python 
  name: tb2l4ydzi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tb2l4ydzi-python 
